/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hiworld;

import org.junit.jupiter.api.Test;

import app.src.main.java.hiworld.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
