/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hiworld;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;

public class App {

    public static void main(String[] args) {
            //for connecting to postgres
            String url = "jdbc:postgresql://localhost:5432/postgres";
            String username = "hiworld";
            String password = "password"; 
      
            try {
               Connection connection = DriverManager.getConnection(url, username, password);

               CustomerDi eDi = new CustomerDi(connection);

               Customer bob = new Customer(0, "Bob", "s", "y", "y");

               eDi.create(bob);
               // Statement statement = connection.createStatement();
               // int rowCount = statement.executeUpdate("insert into customers values (1, 'Diana', 'Vu')");
               // System.out.println(rowCount + " rows affected.");
      
               // ResultSet resultSet = statement.executeQuery("select * from customers");
      
               // while(resultSet.next()){
               //    System.out.println(resultSet.getInt("id"));
               //    System.out.println(resultSet.getString("fname"));
               //    System.out.println(resultSet.getString("lname"));
               // }
               
            } catch (SQLException e) {
               // TODO Auto-generated catch block
               e.printStackTrace();
            }
    }
}
